# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
