# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_auto_20200623_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.CharField(default='berita', max_length=225),
            preserve_default=False,
        ),
    ]
